### PR TITLE
polling for packages and deployments

### PR DESCRIPTION
**Pull request by jackjohn7**
Updating to satisfy [task](https://github.com/orgs/chassyflow/projects/1/views/1?pane=issue&itemId=74489207).

We want to allow a user to decide whether or not to wait for a workflow's associated packages, deployments, and releases to be completed. To do this, we can poll the API for information about the statuses

### CODE REVIEW

**Comment by jackjohn7** [comment]
image
https://github.com/chassyflow/platform/actions/runs/10622490507/job/29449987509

Successfully dogfooding

**Comment by jackjohn7** [comment]
I've verified that when `sync` is disabled, it doesn't bother checking for the success of the workflow.

**Comment by temachy** [comment]
Does the action with `sync = true` wait for all packages and deployments to have status success or error before finishing?

**Review by temachy — APPROVED** [review]
Looks good 👍
Well done!
Feel free to merge

**Pull request merged**
